name: Bot Recompensa

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,2,4,6,8,10,12,14,16,18,20,22 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: node ./node_modules/.bin/playwright install --with-deps

      - name: Run bot
        run: node bot.js
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
